name: Deployments:PR BUGFIXES/FEATURES - Pull Request Against DEV

on:
  pull_request:
    branches:
    - dev 
  push:
    branches:
    - dev 

env:
  SFDX_AUDIENCE_URL: https://test.salesforce.com # Use https://login.salesforce.com for production instances. Use https://test.salesforce.com for sandboxes
  SALESFORCE_ORG_DEV_URL: https://pnnl--pnnldev1.sandbox.my.salesforce.com # Salesforce URL of target org
  SALESFORCE_ORG_USERNAME: builduser@pnnl.doe.pnnldev1 # Salesforce username of target org
  TARGET_BRANCH: dev
  SOURCE_DIR: force-app

jobs:
  Deploy:
    name: Bugfixes/Features Merge-Process 
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_HEAD_REF }}
          fetch-depth: 0
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true
      
      - name: Install SFDX
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin/run plugins --core

      - name: 'Populate auth file with SFDX_URL secret'
        run: |
          echo "${{ secrets.SALESFORCE_AUTHURL_DEV }}" > SFDX_AUTHURL
      
      - name: Authenticate Salesforce Org
        run: |
          node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_AUTHURL -s -a PNNLDev

      - name: Deploy source
        id: Deploy
        if: github.event_name == 'push'
        run:
          node_modules/sfdx-cli/bin/run force:source:deploy -p force-app -u PNNLDev --loglevel fatal --verbose | tee results.txt

      - name: Validate source
        id: validate
        if: github.event_name == 'pull_request'
        run:
          node_modules/sfdx-cli/bin/run force:source:deploy -c -p force-app -u PNNLDev --loglevel fatal --verbose | tee results.txt

      # - name: Run Apex test
      #   run: 
      #     node_modules/sfdx-cli/bin/run force:apex:test:run --resultformat tap --codecoverage -r human -l RunLocalTests -u PNNLDev | tee results.txt
          
      - name: Collect Results
        id: collect-results
        if: ${{ always() }} 
        run: |
          RESULTS=$(cat results.txt)
          echo "$RESULTS"
          RESULTS="${RESULTS//'%'/'%25'}"
          RESULTS="${RESULTS//$'\n'/'%0A'}"
          RESULTS="${RESULTS//$'\r'/'%0D'}"
          echo "::set-output name=results::$RESULTS"
          
      - name: Update Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v5.0.0
        with:
          script: |
            const output = `#### Validation to Salesforce: \`${{ steps.Deploy.outcome }}\`
            
            <details><summary>Show Salesforce Validation Output</summary>
            
            \`\`\`\n
            ${{ steps.collect-results.outputs.results }}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Workflow: \`${{ github.workflow }}\`, Workflow Run Number: \`${{ github.run_number }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
    
  # QADeploy:
  #   name: Call QA Deploy
  #   needs: Deploy
  #   uses: CSGAMERSServices/dhs-us-coast-guard-gangway/.github/workflows/qa-pull-request.yml@uat
  #   secrets:
  #     token: ${{ secrets.JWTKEY }}
